export const strings = {
  en: {
    // Common
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.done': 'Done',
    'common.back': 'Back',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.archive': 'Archive',
    'common.loading': 'Loading…',
    'common.justNow': 'just now',
    'common.minAgo': '{m} min ago',
    'common.hAgo': '{h}h ago',
    'common.dAgo': '{d}d ago',
    'common.tryAgain': 'Try again in a moment.',

    // Tabs
    'tab.today': 'Today',
    'tab.library': 'Library',
    'tab.progress': 'Progress',
    'tab.profile': 'Profile',

    // Today
    'today.heading': 'Today',
    'today.yourQueue': 'Your queue',
    'today.addAnother': 'Add another idea',
    'today.whatsOnMind': "What's on your mind?",
    'today.placeholder': 'e.g., What I want to learn or work on today',
    'today.addToQueue': '📥 Add to queue',
    'today.studyNow': 'Study now →',
    'today.orLetMePick': 'or let me pick',
    'today.surpriseMe': '✨ Surprise me',
    'today.surpriseHint': 'Next on my trail',
    'today.sideBrain': '🧠 Side brain',
    'today.sideBrainHint': 'Outside your usual',
    'today.tellMore.title': 'Tell us more',
    'today.tellMore.bodyChallenge': 'Describe your challenge in a sentence.',
    'today.tellMore.bodyQueue': 'Describe what you want to study in a sentence.',
    'today.couldNotGenerate': 'Could not generate',
    'today.couldNotQueue': 'Could not queue',
    'today.toastBuilding': 'Building cards in the background…',
    'today.buildingCards': 'Building cards…',
    'today.cardsToStudy': '{n} cards to study',
    'today.cardToStudy': '1 card to study',
    'today.ready': 'Ready',

    'today.loading.challenge.1': 'Understanding your context…',
    'today.loading.challenge.2': 'Finding the sharpest angles…',
    'today.loading.challenge.3': 'Picking 3 cards worth your time…',
    'today.loading.surprise.1': 'Reading your trail so far…',
    'today.loading.surprise.2': 'Looking one step ahead…',
    'today.loading.surprise.3': 'Building cards on it…',
    'today.loading.sideBrain.1': 'Stepping outside your usual…',
    'today.loading.sideBrain.2': 'Hunting an idea worth borrowing…',
    'today.loading.sideBrain.3': 'Wiring up the cards…',

    // Card
    'card.study': 'Study',
    'card.studied': '✓ Studied',
    'card.favorite': '☆ Favorite',
    'card.favorited': '★ Favorited',
    'card.next': 'Next →',
    'card.finish': "I'm done!",
    'card.progress': '{i} of {total} · {min} min',
    'cardType.concept': 'Concept',
    'cardType.example': 'Example',
    'cardType.best_practice': 'Best practice',
    'cardType.pitfall': 'Pitfall',
    'cardType.news': 'News',

    // Session
    'session.studiedOfTotal': '{studied} of {total} studied',
    'session.niceWork': 'Nice work',
    'session.xp': '+{xp} XP',
    'session.summary': 'Studied {studied} · Favorited {favorited}',

    // Library
    'library.heading': 'Library',
    'library.tab.tree': 'Tree',
    'library.tab.favorites': 'Favorites',
    'library.treeSubtitle': '{topics} topics across {areas} areas · {cards} cards',
    'library.favoritesSubtitle': '{n} favorites',
    'library.emptyTree': 'Your tree is bare. Generate cards in Today and topics will start branching out here.',
    'library.searchFavorites': 'Search favorites',
    'library.emptyFavorites': 'No favorites yet. Tap "Favorite" on cards in Today to keep them here.',
    'library.noMatches': 'No matches.',
    'library.cardsOnTopic': '{n} cards on this topic',
    'library.close': 'Close',
    'library.otherDomain': 'Other',
    'library.topicOne': '1 topic',
    'library.topicMany': '{n} topics',
    'library.cardOne': '1 card',
    'library.cardMany': '{n} cards',
    'library.moreCount': '+{n} more',
    'library.justRoot': 'Just the root for now',

    // Profile
    'profile.heading': 'Profile',
    'profile.email': 'Email',
    'profile.role': 'Role',
    'profile.experience': 'Experience',
    'profile.experienceValue': '{n} yrs',
    'profile.interests': 'Interests',
    'profile.tapEdit': 'Tap Edit to choose',
    'profile.language': 'Language',
    'profile.signOut': 'Sign out',

    // Edit Interests Modal
    'interests.title': 'Interests',
    'interests.subtitle': 'Tap a category to expand. Add your own below.',
    'interests.addYourOwn': 'Add your own',
    'interests.placeholder': 'e.g., Sourdough, Brazilian jiu-jitsu, Tax law',
    'interests.add': 'Add',
    'interests.selected': '{n} of {max} selected',
    'interests.pickAtLeastOne.title': 'Pick at least one',
    'interests.pickAtLeastOne.body': 'Cards work better with at least one interest.',
    'interests.tooLong.title': 'Too long',
    'interests.tooLong.body': 'Keep interests under 40 characters.',
    'interests.limitReached.title': 'Limit reached',
    'interests.limitReached.body': 'Up to {max} interests.',
    'interests.couldNotSave': 'Could not save',

    // Onboarding
    'onb.role.title': "What's your role?",
    'onb.role.subtitle': 'Pick the closest match.',
    'onb.exp.title': 'Years of experience',
    'onb.exp.subtitle': 'Cards will adjust to your level.',
    'onb.interests.title': 'What interests you?',
    'onb.interests.subtitle': 'Tap a category to expand. Pick up to {max} across any.',
    'onb.goal.title': 'Your goal',
    'onb.goal.subtitle': 'One sentence — what do you want to grow into?',
    'onb.goal.placeholder': 'e.g., be a calmer, more present parent',
    'onb.time.title': 'When do you study?',
    'onb.time.subtitle': "We'll send a gentle reminder around then.",
    'onb.continue': 'Continue',
    'onb.finish': 'Finish',
    'onb.couldNotSaveProfile': 'Could not save profile',
    'onb.couldNotSaveSettings': 'Could not save settings',

    // Roles
    'role.backend': 'Backend dev',
    'role.frontend': 'Frontend dev',
    'role.fullstack': 'Fullstack',
    'role.mobile': 'Mobile dev',
    'role.data': 'Data engineer',
    'role.devops': 'DevOps / SRE',
    'role.ml': 'ML engineer',
    'role.lead': 'Tech lead',

    // Experience labels
    'exp.0-2': '0-2 yrs',
    'exp.3-5': '3-5 yrs',
    'exp.6-10': '6-10 yrs',
    'exp.10plus': '10+ yrs',

    // Queue actions
    'queue.deleteTitle': 'Delete from queue?',
    'queue.deleteBody': 'This permanently removes the session and its cards.',

    // Auth / login (kept minimal; login screen not deeply translated yet)
    'auth.signIn': 'Sign in',

    // Language picker
    'lang.title': 'Language',
    'lang.en': 'English',
    'lang.pt': 'Português',
  },

  pt: {
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.done': 'Pronto',
    'common.back': 'Voltar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.archive': 'Arquivar',
    'common.loading': 'Carregando…',
    'common.justNow': 'agora',
    'common.minAgo': '{m} min atrás',
    'common.hAgo': '{h}h atrás',
    'common.dAgo': '{d}d atrás',
    'common.tryAgain': 'Tente novamente em instantes.',

    'tab.today': 'Hoje',
    'tab.library': 'Biblioteca',
    'tab.progress': 'Progresso',
    'tab.profile': 'Perfil',

    'today.heading': 'Hoje',
    'today.yourQueue': 'Sua fila',
    'today.addAnother': 'Adicionar outra ideia',
    'today.whatsOnMind': 'O que está na sua cabeça?',
    'today.placeholder': 'ex: o que quero aprender ou trabalhar hoje',
    'today.addToQueue': '📥 Adicionar à fila',
    'today.studyNow': 'Estudar agora →',
    'today.orLetMePick': 'ou deixe comigo',
    'today.surpriseMe': '✨ Me surpreenda',
    'today.surpriseHint': 'Próximo passo da sua trilha',
    'today.sideBrain': '🧠 Mente lateral',
    'today.sideBrainHint': 'Fora do seu usual',
    'today.tellMore.title': 'Conta mais',
    'today.tellMore.bodyChallenge': 'Descreva seu desafio em uma frase.',
    'today.tellMore.bodyQueue': 'Descreva o que você quer estudar em uma frase.',
    'today.couldNotGenerate': 'Não consegui gerar',
    'today.couldNotQueue': 'Não consegui adicionar',
    'today.toastBuilding': 'Gerando cards em segundo plano…',
    'today.buildingCards': 'Gerando cards…',
    'today.cardsToStudy': '{n} cards pra estudar',
    'today.cardToStudy': '1 card pra estudar',
    'today.ready': 'Pronto',

    'today.loading.challenge.1': 'Entendendo seu contexto…',
    'today.loading.challenge.2': 'Buscando os ângulos certos…',
    'today.loading.challenge.3': 'Escolhendo 3 cards pra você…',
    'today.loading.surprise.1': 'Lendo sua trilha até aqui…',
    'today.loading.surprise.2': 'Olhando um passo à frente…',
    'today.loading.surprise.3': 'Montando os cards…',
    'today.loading.sideBrain.1': 'Saindo do seu usual…',
    'today.loading.sideBrain.2': 'Caçando uma ideia interessante…',
    'today.loading.sideBrain.3': 'Montando os cards…',

    'card.study': 'Estudar',
    'card.studied': '✓ Estudado',
    'card.favorite': '☆ Favoritar',
    'card.favorited': '★ Favoritado',
    'card.next': 'Próximo →',
    'card.finish': 'Estudei!',
    'card.progress': '{i} de {total} · {min} min',
    'cardType.concept': 'Conceito',
    'cardType.example': 'Exemplo',
    'cardType.best_practice': 'Boa prática',
    'cardType.pitfall': 'Armadilha',
    'cardType.news': 'Novidade',

    'session.studiedOfTotal': '{studied} de {total} estudados',
    'session.niceWork': 'Boa!',
    'session.xp': '+{xp} XP',
    'session.summary': 'Estudados {studied} · Favoritados {favorited}',

    'library.heading': 'Biblioteca',
    'library.tab.tree': 'Árvore',
    'library.tab.favorites': 'Favoritos',
    'library.treeSubtitle': '{topics} tópicos em {areas} áreas · {cards} cards',
    'library.favoritesSubtitle': '{n} favoritos',
    'library.emptyTree': 'Sua árvore está vazia. Gere cards na aba Hoje e os tópicos vão crescendo aqui.',
    'library.searchFavorites': 'Buscar favoritos',
    'library.emptyFavorites': 'Nenhum favorito ainda. Toque em "Favoritar" nos cards pra guardar aqui.',
    'library.noMatches': 'Sem resultados.',
    'library.cardsOnTopic': '{n} cards neste tópico',
    'library.close': 'Fechar',
    'library.otherDomain': 'Outros',
    'library.topicOne': '1 tópico',
    'library.topicMany': '{n} tópicos',
    'library.cardOne': '1 card',
    'library.cardMany': '{n} cards',
    'library.moreCount': '+{n}',
    'library.justRoot': 'Só a raiz por enquanto',

    'profile.heading': 'Perfil',
    'profile.email': 'Email',
    'profile.role': 'Função',
    'profile.experience': 'Experiência',
    'profile.experienceValue': '{n} anos',
    'profile.interests': 'Interesses',
    'profile.tapEdit': 'Toque em Editar pra escolher',
    'profile.language': 'Idioma',
    'profile.signOut': 'Sair',

    'interests.title': 'Interesses',
    'interests.subtitle': 'Toque numa categoria pra expandir. Adicione os seus abaixo.',
    'interests.addYourOwn': 'Adicione o seu',
    'interests.placeholder': 'ex: Fermentação natural, Jiu-jitsu, Direito tributário',
    'interests.add': 'Adicionar',
    'interests.selected': '{n} de {max} selecionados',
    'interests.pickAtLeastOne.title': 'Escolha pelo menos um',
    'interests.pickAtLeastOne.body': 'Os cards ficam melhores com pelo menos um interesse.',
    'interests.tooLong.title': 'Muito longo',
    'interests.tooLong.body': 'Mantenha o interesse com menos de 40 caracteres.',
    'interests.limitReached.title': 'Limite atingido',
    'interests.limitReached.body': 'Até {max} interesses.',
    'interests.couldNotSave': 'Não consegui salvar',

    'onb.role.title': 'Qual é sua função?',
    'onb.role.subtitle': 'Escolha a opção mais próxima.',
    'onb.exp.title': 'Anos de experiência',
    'onb.exp.subtitle': 'Os cards vão se ajustar ao seu nível.',
    'onb.interests.title': 'O que te interessa?',
    'onb.interests.subtitle': 'Toque numa categoria pra expandir. Escolha até {max} entre todas.',
    'onb.goal.title': 'Seu objetivo',
    'onb.goal.subtitle': 'Uma frase — no que você quer crescer?',
    'onb.goal.placeholder': 'ex: ser um pai mais calmo e presente',
    'onb.time.title': 'Quando você estuda?',
    'onb.time.subtitle': 'Vou te lembrar com gentileza por volta deste horário.',
    'onb.continue': 'Continuar',
    'onb.finish': 'Concluir',
    'onb.couldNotSaveProfile': 'Não consegui salvar o perfil',
    'onb.couldNotSaveSettings': 'Não consegui salvar as configurações',

    'role.backend': 'Dev Backend',
    'role.frontend': 'Dev Frontend',
    'role.fullstack': 'Fullstack',
    'role.mobile': 'Dev Mobile',
    'role.data': 'Eng. de Dados',
    'role.devops': 'DevOps / SRE',
    'role.ml': 'Eng. de ML',
    'role.lead': 'Tech Lead',

    'exp.0-2': '0-2 anos',
    'exp.3-5': '3-5 anos',
    'exp.6-10': '6-10 anos',
    'exp.10plus': '10+ anos',

    'queue.deleteTitle': 'Remover da fila?',
    'queue.deleteBody': 'Isso remove permanentemente a sessão e os cards dela.',

    'auth.signIn': 'Entrar',

    'lang.title': 'Idioma',
    'lang.en': 'English',
    'lang.pt': 'Português',
  },
} as const;

export type StringKey = keyof typeof strings.en;
