insert into public.achievements (id, name, description, icon, xp_reward) values
  ('first-card', 'First Card', 'Studied your very first card.', 'sparkles', 25),
  ('daily-3', 'Daily Three', 'Completed a session of 3+ cards in one day.', 'check-circle', 30),
  ('week-streak-1', 'Week Warrior', 'Hit your weekly goal (5 active days).', 'flame', 50),
  ('week-streak-4', 'Monthly Mind', '4 weekly goals in a row.', 'crown', 200),
  ('deep-dive', 'Deep Diver', 'Used Deepen on 10 cards.', 'anchor', 75),
  ('topic-master', 'Topic Master', 'Studied 5 cards from the same topic.', 'target', 60),
  ('polyglot', 'Polyglot', 'Touched 5 different interest areas.', 'globe', 60),
  ('early-bird', 'Early Bird', 'Studied before 8am 5 times.', 'sunrise', 50),
  ('night-owl', 'Night Owl', 'Studied after 10pm 5 times.', 'moon', 50),
  ('marathon', 'Marathon', 'Studied 10 cards in a single day.', 'zap', 80),
  ('feedback-king', 'Feedback King', 'Rated 50 cards.', 'thumbs-up', 60),
  ('explorer', 'Explorer', 'Discovered 50 different topics.', 'compass', 100)
on conflict (id) do nothing;

insert into public.topics (slug, name, description, verified) values
  ('frontend', 'Frontend', 'Frontend engineering', true),
  ('backend', 'Backend', 'Backend engineering', true),
  ('devops', 'DevOps', 'DevOps and infrastructure', true),
  ('ai-ml', 'AI / ML', 'Artificial intelligence and machine learning', true),
  ('data', 'Data Engineering', 'Data engineering and analytics', true),
  ('mobile', 'Mobile', 'Mobile development', true),
  ('security', 'Security', 'Application and infrastructure security', true),
  ('architecture', 'Software Architecture', 'System design and architecture', true),
  ('testing', 'Testing', 'Testing strategies and practices', true),
  ('databases', 'Databases', 'Database systems', true),
  ('javascript', 'JavaScript', 'JavaScript language', true),
  ('typescript', 'TypeScript', 'TypeScript language', true),
  ('react', 'React', 'React library', true),
  ('react-native', 'React Native', 'React Native', true),
  ('node', 'Node.js', 'Node.js runtime', true),
  ('python', 'Python', 'Python language', true),
  ('go', 'Go', 'Go language', true),
  ('rust', 'Rust', 'Rust language', true),
  ('postgres', 'PostgreSQL', 'PostgreSQL database', true),
  ('redis', 'Redis', 'Redis in-memory store', true),
  ('docker', 'Docker', 'Docker containers', true),
  ('kubernetes', 'Kubernetes', 'Kubernetes orchestration', true),
  ('aws', 'AWS', 'Amazon Web Services', true),
  ('gcp', 'Google Cloud', 'Google Cloud Platform', true),
  ('azure', 'Azure', 'Microsoft Azure', true),
  ('terraform', 'Terraform', 'Infrastructure as code', true),
  ('graphql', 'GraphQL', 'GraphQL APIs', true),
  ('rest-api', 'REST APIs', 'REST API design', true),
  ('grpc', 'gRPC', 'gRPC protocol', true),
  ('microservices', 'Microservices', 'Microservices architecture', true),
  ('event-driven', 'Event-Driven Architecture', 'Event-driven systems', true),
  ('kafka', 'Kafka', 'Apache Kafka', true),
  ('rate-limiting', 'Rate Limiting', 'Rate limiting strategies', true),
  ('caching', 'Caching', 'Caching strategies', true),
  ('observability', 'Observability', 'Logs, metrics, traces', true),
  ('ci-cd', 'CI/CD', 'Continuous integration and delivery', true),
  ('git', 'Git', 'Git version control', true),
  ('llm', 'LLMs', 'Large language models', true),
  ('rag', 'RAG', 'Retrieval-augmented generation', true),
  ('vector-db', 'Vector Databases', 'Vector databases and embeddings', true),
  ('prompt-engineering', 'Prompt Engineering', 'Prompt engineering', true),
  ('agents', 'AI Agents', 'AI agentic systems', true),
  ('streaming', 'Data Streaming', 'Real-time streaming', true),
  ('queues', 'Message Queues', 'Async messaging', true),
  ('auth', 'Authentication', 'Auth and identity', true),
  ('encryption', 'Encryption', 'Encryption and crypto', true),
  ('performance', 'Performance', 'Performance optimization', true),
  ('accessibility', 'Accessibility', 'Web/mobile accessibility', true),
  ('design-systems', 'Design Systems', 'UI design systems', true),
  ('product-eng', 'Product Engineering', 'Product engineering practices', true)
on conflict (slug) do nothing;
